version: "3"
services:
    node-docker:
        image: selenium/node-docker:4.8.0-20230123
        volumes:
            - ./assets:/opt/selenium/assets
            - ./config.toml:/opt/bin/config.toml
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - selenium-hub
        environment:
            SE_EVENT_BUS_HOST: selenium-hub
            SE_EVENT_BUS_PUBLISH_PORT: 4442
            SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            SCREEN_DEPTH: 24
        networks:
            - grid

    selenium-hub:
        image: selenium/hub:4.8.0-20230123
        container_name: selenium-hub
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
        networks:
            - grid

    backend:
        image: paulogoncalvesbh/serverest:latest
        container_name: serverest-backend
        ports:
            - 3000:3000
        networks:
            - grid

    frontend:
        build:
            context: ../application
            dockerfile: Dockerfile
        container_name: serverest-frontend
        ports:
            - 3001:3001
        networks:
            - grid

networks:
    grid:
        name: selenium-grid
